package com.mahmoud.altasherat.common.domain.util.error

enum class ValidationError : AltasheratError {
    INVALID_EMAIL,
    EMPTY_EMAIL,
    INVALID_PASSWORD,
    EMPTY_PASSWORD,
    EMPTY_FIRSTNAME,
    INVALID_FIRSTNAME,
    INVALID_MIDDLE_NAME,
    EMPTY_LASTNAME,
    INVALID_LASTNAME,
    EMPTY_PHONE_NUMBER,
    INVALID_PHONE_NUMBER,
    EMPTY_COUNTRY_CODE,
    INVALID_COUNTRY_CODE,
    INVALID_IMAGE_EXTENSION,
    INVALID_IMAGE_SIZE
}